name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"
      - name: Install Python
        run: uv python install
      - name: Run pre-commit
        run: uv run --no-sync --with pre-commit-uv pre-commit run --show-diff-on-failure --color=always --all-files

  pytest:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    name: PyTest
    needs: [pre-commit]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"
      - name: Install Project
        run: uv python pin ${{ matrix.python_version }} && uv sync --dev --no-extra vllm --extra test
      - name: Run PyTest
        run: uv run pytest
